### ISSUE TITLE
Error generating model

### ISSUE THREAD

**Issue by commadelimited** [modocache/django-generate-scaffold#29]
I'm using django-generate-scaffold for the first time and I'm getting errors when running the `generatescaffold` command. I'm still fairly new to Python/Django and I'm the one setting up my app (also for the first time). Here's some pertinent information.
#### The tree

```
├── bookreview
│   ├── __init__.py
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
├── books
│   ├── __init__.py
│   ├── admin.py
│   ├── models.py
│   ├── tests.py
│   └── views.py
├── fabfile.py
├── manage.py
└── requirements.txt
```
### The requirements.txt (after pip freeze)

```
Django==1.6.2
Fabric==1.8.1
django-generate-scaffold==0.0.5a0
djangorestframework==2.3.12
ecdsa==0.10
paramiko==1.12.1
pycrypto==2.6.1
wsgiref==0.1.2
```
#### The command:

`python manage.py generatescaffold books Author first_name:string last_name:string`
### The error:

```
            backup  books/models.py
            revert  books/models.py
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/andymatthews/.virtualenvs/drf/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/andymatthews/.virtualenvs/drf/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/andymatthews/.virtualenvs/drf/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/andymatthews/.virtualenvs/drf/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/andymatthews/.virtualenvs/drf/lib/python2.7/site-packages/generate_scaffold/management/commands/generatescaffold.py", line 65, in handle
    self.generate_scaffold(*args, **options)
  File "/Users/andymatthews/.virtualenvs/drf/lib/python2.7/site-packages/generate_scaffold/management/commands/generatescaffold.py", line 169, in generate_scaffold
    reload_django_appcache()
  File "/Users/andymatthews/.virtualenvs/drf/lib/python2.7/site-packages/generate_scaffold/utils/cacheclear.py", line 16, in reload_django_appcache
    for app in cache.get_apps():
  File "/Users/andymatthews/.virtualenvs/drf/lib/python2.7/site-packages/django/db/models/loading.py", line 139, in get_apps
    self._populate()
  File "/Users/andymatthews/.virtualenvs/drf/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/Users/andymatthews/.virtualenvs/drf/lib/python2.7/site-packages/django/db/models/loading.py", line 95, in load_app
    self.handled.add(app_name)
AttributeError: 'dict' object has no attribute 'add'
```

**Comment by modocache** [comment]
Sorry for the frustration, I remember I hit a lot of road blocks when I was getting started with Django. Would you mind showing me what's inside of your `books/models.py`?

**Comment by modocache** [comment]
It's also possible this no longer works on the latest version of Django--1.6.2 in your case. I'll look into it sometime in the coming days. Sorry for the inconvenience. Until then, you could try downgrading to Django 1.5.

Thanks for the issue!

**Comment by commadelimited** [comment]
I don't mind downgrading. I'm writing an article on Django Rest Framework. I plan on generating the base Django code for the user so they don't have to take time focusing on that. Thanks for the suggestion.

**Comment by modocache** [comment]
No problem. Let me know if you experience trouble on Django 1.5 or prior.

**Comment by commadelimited** [comment]
Will do. Thanks.

**Comment by commadelimited** [comment]
FWIW I downgraded Django to 1.5.1 and scaffolding ran flawlessly, thanks.

**Comment by Phlip** [comment]
and it looks like Django 1.7's "best scaffold generator" pole-position is wide open... C-;

(I'm here 'cause I hit the bug. Installing Django 1.5 now.)
